### ISSUE TITLE
Add a configuration option to allow confirmations to be ephemeral

### ISSUE THREAD

**Issue by AriannaStory** [reminder-bot/reminder-rs#14]
It would be nice if I could set the confirmation messages to be ephemeral. I use reminder-bot in a server with my girlfriend, and they're just a bit too large. It'd help us out a bunch to just keep the confirmations to ourselves. Thanks for the consideration!

**Comment by JellyWX** [comment]
I've added this on the next branch over at gitea.jellypro.xyz/jude/reminder-bot, but it likely won't be available on the hosted bot for a bit longer. You can follow the instructions over there to set up your own hosted version if you like, otherwise I'll post an announcement in the Discord when the public version is updated

**Comment by JellyWX** [comment]
This is live now, under "/settings ephemeral on/off"
